FROM kalilinux/kali-rolling

# Обновляем пакеты и ставим базовые инструменты для пентеста
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
      iproute2 \
      inetutils-ping \
      net-tools \
      dnsutils \
      nmap \
      gobuster \
      ffuf \
      sqlmap \
      curl \
      git \
      tcpdump \
      traceroute \
      netcat-traditional \
      iputils-tracepath \
      ca-certificates && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN mkdir -p /root/loot

